# @format

name: Deploy Latihan Nginx

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: windows-latest # Untuk menjalankan di lingkungan Windows
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t asia-southeast2-docker.pkg.dev/$GOOGLE_PROJECT/latihan1/nginx:latest . 
          docker push asia-southeast2-docker.pkg.dev/$GOOGLE_PROJECT/latihan1/nginx:latest .
